project_id = "dvauueqtqrveqcckfrjx"

[functions.signup-user]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false

[functions.login-otp]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.google-maps-key]
verify_jwt = false
