// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/list-offers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.110.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
function notAuthenticated() {
  return {
    content: [{ type: "text", text: "Not authenticated. Sign in to this app first." }],
    isError: true
  };
}

// src/lib/mcp/tools/list-offers.ts
var list_offers_default = defineTool({
  name: "list_offers",
  title: "List offers",
  description: "List active FamePass venue offers/campaigns, optionally filtered by city, offer type, or a text search on the title.",
  inputSchema: {
    search: z.string().trim().min(1).optional().describe("Text to match in the offer title."),
    city: z.string().trim().min(1).optional().describe("Filter by venue city."),
    offer_type: z.string().trim().min(1).optional().describe("Filter by offer type."),
    limit: z.number().int().min(1).max(50).default(20).describe("Max offers to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ search, city, offer_type, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("offers").select(
      "id, title, description, offer_type, value_worth, min_followers, starts_at, ends_at, cover_image_url, venues(id, name, city, category, logo_url)"
    ).eq("is_active", true).order("created_at", { ascending: false }).limit(limit ?? 20);
    if (search) query = query.ilike("title", `%${search}%`);
    if (offer_type) query = query.eq("offer_type", offer_type);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    let offers = data ?? [];
    if (city) {
      const needle = city.toLowerCase();
      offers = offers.filter((o) => (o.venues?.city ?? "").toLowerCase().includes(needle));
    }
    return {
      content: [{ type: "text", text: JSON.stringify(offers, null, 2) }],
      structuredContent: { offers, count: offers.length }
    };
  }
});

// src/lib/mcp/tools/get-offer.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_offer_default = defineTool2({
  name: "get_offer",
  title: "Get offer",
  description: "Get the full details of a single FamePass offer, including the venue that published it.",
  inputSchema: { offer_id: z2.string().uuid().describe("The offer id.") },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ offer_id }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("offers").select(
      "*, venues(id, name, city, country, category, description, logo_url, cover_image_url), categories(id, name)"
    ).eq("id", offer_id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Offer not found." }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { offer: data }
    };
  }
});

// src/lib/mcp/tools/list-my-bookings.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_my_bookings_default = defineTool3({
  name: "list_my_bookings",
  title: "List my bookings",
  description: "List the signed-in user's FamePass bookings (as influencer, or as venue owner for their venues), newest first.",
  inputSchema: {
    status: z3.string().trim().min(1).optional().describe("Filter by booking status, e.g. upcoming, checked_in, completed."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("bookings").select("id, status, scheduled_date, checked_in_at, completed_at, notes, offer_id, venue_id, influencer_id, offers(title), venues(name, city)").order("created_at", { ascending: false }).limit(limit ?? 20);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const bookings = data ?? [];
    return {
      content: [{ type: "text", text: JSON.stringify(bookings, null, 2) }],
      structuredContent: { bookings, count: bookings.length }
    };
  }
});

// src/lib/mcp/tools/apply-to-offer.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var apply_to_offer_default = defineTool4({
  name: "apply_to_offer",
  title: "Apply to an offer",
  description: "Apply the signed-in influencer to a FamePass offer. Creates a pending redemption the venue can approve.",
  inputSchema: {
    offer_id: z4.string().uuid().describe("The offer to apply to."),
    preferred_date: z4.string().trim().min(1).optional().describe("Preferred visit date, ISO format (YYYY-MM-DD).")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ offer_id, preferred_date }, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const { data: existing } = await supabase.from("offer_redemptions").select("id, status").eq("offer_id", offer_id).eq("influencer_id", userId).maybeSingle();
    if (existing) {
      return {
        content: [{ type: "text", text: `Already applied. Current status: ${existing.status}.` }],
        structuredContent: { redemption: existing, already_applied: true }
      };
    }
    const { data, error } = await supabase.from("offer_redemptions").insert({ offer_id, influencer_id: userId, preferred_date: preferred_date ?? null, status: "pending" }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Applied. Redemption ${data?.id} is pending venue approval.` }],
      structuredContent: { redemption: data }
    };
  }
});

// src/lib/mcp/tools/get-my-profile.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var get_my_profile_default = defineTool5({
  name: "get_my_profile",
  title: "Get my profile",
  description: "Get the signed-in user's FamePass profile (name, handles, followers, score) and the venues they own, if any.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) return notAuthenticated();
    const supabase = supabaseForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: profile, error }, { data: venues }] = await Promise.all([
      supabase.from("profiles").select("full_name, bio, city, country, avatar_url, instagram_handle, tiktok_handle, followers_count, tiktok_followers, engagement_rate, influencer_score, badge, niche, approval_status").eq("user_id", userId).maybeSingle(),
      supabase.from("venues").select("id, name, city, category, approval_status, is_active").eq("owner_id", userId)
    ]);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const result = { profile: profile ?? null, venues: venues ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "dvauueqtqrveqcckfrjx";
var mcp_default = defineMcp({
  name: "remix-of-connect-create-platform",
  title: "Remix of Connect & Create Platform",
  version: "0.1.0",
  instructions: "Tools for the FamePass platform, which connects influencers with venues. Use `list_offers` and `get_offer` to browse venue campaigns, `apply_to_offer` to apply as the signed-in influencer, `list_my_bookings` to track bookings, and `get_my_profile` for the signed-in user's profile and venues. All data is scoped to the signed-in user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [list_offers_default, get_offer_default, apply_to_offer_default, list_my_bookings_default, get_my_profile_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
