ALTER TABLE public.campaigns
  ADD COLUMN IF NOT EXISTS content_focus text,
  ADD COLUMN IF NOT EXISTS dietary_options text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS require_phone boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS age_restricted boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS age_limit int,
  ADD COLUMN IF NOT EXISTS invite_only boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS instagram_offers jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS tiktok_offers jsonb DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS handles text[] DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS deliverables jsonb DEFAULT '{}'::jsonb,
  ADD COLUMN IF NOT EXISTS allow_post_or_reel boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS availability_type text DEFAULT 'ongoing',
  ADD COLUMN IF NOT EXISTS visible_before_start boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS required_days_notice int DEFAULT 3,
  ADD COLUMN IF NOT EXISTS available_days text[] DEFAULT '{Mon,Tue,Wed,Thu,Fri,Sat,Sun}',
  ADD COLUMN IF NOT EXISTS booking_limits boolean DEFAULT false,
  ADD COLUMN IF NOT EXISTS approval_type text DEFAULT 'manual',
  ADD COLUMN IF NOT EXISTS auto_approve_top boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS is_draft boolean DEFAULT true,
  ADD COLUMN IF NOT EXISTS cover_video_url text,
  ADD COLUMN IF NOT EXISTS cover_images text[] DEFAULT '{}';